### ISSUE TITLE
Not working with the latest patch

### ISSUE THREAD

**Issue by andronikos9217** [WittleWolfie/ModMenu#11]
The game stuck on loading screen while this mod activated. Please fix it.

**Comment by WittleWolfie** [comment]
I do not have any issues and none have been reported. Please share your log files.

**Comment by andronikos9217** [comment]
My apologies. It seems that another mod using Mod Menu was the problem.

**Comment by WittleWolfie** [comment]
No worries! Glad you figured it out.
