### ISSUE TITLE
You said to mention if controller support was needed

### ISSUE THREAD

**Issue by coyoteconscious** [WittleWolfie/ModMenu#14]
I am disabled, and pretty much if a game requires a keyboard and mouse, I cannot play it. I suspect I might not be the only person with that problem.

**Comment by WittleWolfie** [comment]
Hey @coyoteconscious, unfortunately I'm not modding anymore. I did look into this (and asked another modder), but adding controller support is pretty extensive. It requires re-creating a significant portion of the mod.

What you can do is manually edit the settings file to change settings: `%AppData%\..\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous\general_settings.json`.

I'm leaving this issue open in case others run into it.

**Comment by WittleWolfie** [comment]
So it looks like the new fork of this mod might have some limited controller support: https://github.com/CasDragon/ModMenu/.

Otherwise you can request there, good luck!
