### ISSUE TITLE
Issue Loading Mod

### ISSUE THREAD

**Issue by AzuretheKobold** [WittleWolfie/ModMenu#15]
So after some testing, and fiddling with my mods as of latest update for dance of masks this mod will freeze during initial loading of the game and gives an endless load screen. No other mod seems to be doing this, but the moment i try to load this mod it will cause the endless load screen. So it seems to be this mod in question causing the issue, i can only assume it needs to be updated to the latest patch BUT thought i would mention it at least.

**Comment by WittleWolfie** [comment]
I can't reproduce this. Can you post your logs? Use this guide: https://github.com/cabarius/ToyBox/wiki/Diagnosing-Loading-Problems

**Comment by biship** [comment]
https://gist.github.com/biship/9934b11777b89e9a9936ca4fbf24fd10

Below are my mods. All updated in the last 2 days, after the patch/DLC.
They all work fine, without ModMenu.
When I add ModMenu, then loading the game hangs at the usual ~70% progress bar on the loading screen.
Any tips or anything else you need? Thanks for the great mod BTW.

d----           6/14/2024  3:46 PM                0ToyBox0
d----           6/14/2024  4:07 PM                AlternateRacialTraits
d----           6/14/2024  1:59 PM                BubbleBuffs
d----           6/14/2024  3:39 PM                CharacterOptionsPlus
d----           6/14/2024  4:08 PM                ExpandedContent
d----           6/14/2024  2:00 PM                MicroscopicContentExpansion
d----           6/14/2024  4:07 PM                MiscTweaksAndFixes
d----           5/29/2024 10:32 AM                ModMenu
d----           6/14/2024  4:07 PM                PrestigePlus
d----           6/14/2024  2:00 PM                RandomEquipment
d----           6/14/2024  3:46 PM                RespecWrath
d----           6/14/2024  2:00 PM                TabletopTweaks-Base
d----           6/14/2024  1:59 PM                TabletopTweaks-Core
d----           6/14/2024  2:00 PM                TabletopTweaks-Flanking
d----           6/14/2024  2:00 PM                TabletopTweaks-Reworks
d----           6/14/2024  2:00 PM                WOTR_MAKING_FRIENDS
d----           6/14/2024  4:09 PM                WrathPatches

**Comment by CarbonLight** [comment]
Looks like a conflict between expandedcontent and prestige plus - I just assume removing modmenu breaks prestige plus and then the game loads, but I was having the same issue the it crashed on expanded content.

**Comment by WittleWolfie** [comment]
Glad you like the mod @biship. Nothing obvious in the log file; I'm not very active these days but I'll try to take a look next week.

You can also look into the Expanded Content / Prestige Plus issue and let me know if that helps.

**Comment by AzuretheKobold** [comment]
Just an update from my end---

Updated Prestige Plus, Dark Codex and Expanded Content and seems to be working again! guess wasnt this mod specifically. Odd how those mods would load up without mod menu (wouldnt work without mod menu, but would still load up). But the updates seemed to fix it so all is good on my end. 

I guess its just the pains of a new update.
