### ISSUE TITLE
Game Settings Blank with Mode Menu installed

### ISSUE THREAD

**Issue by Ner013** [WittleWolfie/ModMenu#16]
First I want to say thank you for all your hard work with this and for making other mods possible.

It seems like the last update to the game has made it so that with Mod Menu installed the Game Settings Menu is Blank.

![ModMenuBug](https://github.com/user-attachments/assets/be6a9b21-8ca3-44d2-81e5-c69eaca07ae0)

I have tried uninstalling all other mods and reinstalling one by one and this is the only one when uninstalled the issue happens.

**Comment by WittleWolfie** [comment]
Thanks for the report. I've got a fix I can hopefully publish later today.

**Comment by WittleWolfie** [comment]
This mod has been taken over by some other modders in the community: https://github.com/CasDragon/ModMenu/. If you're using ModFinder to install it will update and fix this automatically.
