### ISSUE TITLE
Keybindings no longer work when you load a game from the main menu.

### ISSUE THREAD

**Issue by Balkoth-dev** [WittleWolfie/ModMenu#2]
Steps to reproduce:
1: Load game with a keybinding set
2: Test to see if keybinding is working
3: Load to main menu
4: Reload game
5: Attempt to use keybinding again.

**Comment by WittleWolfie** [comment]
Weeird. They must be re-loading keybindings, so I'll have to patch and re-register it. Can fix this week.
