### ISSUE TITLE
Need for dynamic settings

### ISSUE THREAD

**Issue by zephe0n** [WittleWolfie/ModMenu#4]
I'm in need of some way to dynamically modify mod settings. The use case would be a character whitelist for AutoMount. It not only depends on a loaded save but also on companions/mercenaries that might be added/removed.

Any ideas? I'm aware that it creates a save dependecy so it might be out of scope.

Probably just adding accessors for removing/modifying menu entries would be enough as I could manage saved settings externally and delay menu creation (or at least the dynamic part) until a save is loaded.

**Comment by WittleWolfie** [comment]
A few thoughts:

1. Dynamic strings - The ability to basically have a callback which provides the string for a setting so you can have them be named. Basically same as the 6 slots approach but nicer UI. Should be easy.
2. Party Selector - A section of character specific settings with a UI to select which character you're working with. More work, very cool UI.
3. Dynamic Menu Entries - Don't know how to implement this off the top of my head.

I think Bubbles can help w/ 2 so I'm inclined to investigate that route. But 1 might be useful anyways and I think is pretty easy to do.

Thoughts?

**Comment by factubsio** [comment]
Yeah 2 not hard if we don't care about super  edge cases with parties with 950 mercs.

**Comment by zephe0n** [comment]
2 is definitely nicer but is not mutually exclusive with 1, which might have some other use cases. I'm could use any of them both.
