### ISSUE TITLE
Unknown key: modsmenu.title when changing display language

### ISSUE THREAD

**Issue by apocc** [WittleWolfie/ModMenu#6]
When I change the display language the mod menu tab shows that the current localisation pack is missing the ModMenu title entry.

Tested with game v2.0.2.c and ModMenu v1.2.5

**Comment by WittleWolfie** [comment]
How important is this? It doesn't support localization since I didn't want to depend on any other libs (BPCore or TTT-Core) and I didn't want to re-implement for the mod. I can probably do a simpler form of localization though.

**Comment by WittleWolfie** [comment]
(To clarify: when you restart the game it should display "Mods" regardless of locale.)

**Comment by apocc** [comment]
It's not that big a deal. I just noticed it when implementing the localisation for the Hotkeys ModMenu port. Everything remains functional and switching languages shouldn't be that frequent.

**Comment by WittleWolfie** [comment]
Added w/ RU localization.
