### ISSUE TITLE
OnPress event of bound key fires multiple times

### ISSUE THREAD

**Issue by apocc** [WittleWolfie/ModMenu#7]
It seems the `OnPress` event of a bound key via ModMenu is fired multiple times (UMM log):

- twice after starting the game
- three times after loading a save

When I then exit to the main menu everything seems to be normal.

Tested with game v2.0.3i and ModMenu v1.2.5

Edit:
`RenewRegisteredBindings` doesn't remove the callback binding in `m_BindingCallbacks`. Rebinding the key just adds the same callback to `m_BindingCallbacks`.

A `DoUnbind` before [binding the key](https://github.com/WittleWolfie/ModMenu/blob/main/ModMenu/Settings/KeyBinding.cs#L145) removes the callback.

```C#
if (Game.Instance.Keyboard.GetBindingByName(keyBinding.Entity.Key) != null)
{
  Main.Logger.Log($"Unbinding key: {keyBinding.Entity.Key}");
  Game.Instance.Keyboard.DoUnbind(keyBinding.Entity.Key, keyBinding.OnPress);
}

Game.Instance.Keyboard.Bind(keyBinding.Entity.Key, keyBinding.OnPress);
```

**Comment by WittleWolfie** [comment]
Thanks! I'll take a look this weekend.

**Comment by WittleWolfie** [comment]
BTW feel free to submit PRs if you've got a fix. Happy to have external contributions.
