### ISSUE TITLE
[request] Extended dates for mod info

### ISSUE THREAD

**Issue by Dark0Zero** [WittleWolfie/ModMenu#9]
A lot of the mods this program is finding are from last year or older. I've found a few that appeared to be recent, seemingly only a few days old, suggesting they are compatible with the current build, however only because I actually check the target was aware that a number of seemingly recent mods are actually a year old or so.

**Comment by WittleWolfie** [comment]
I don't follow. Are you saying that the last updated date is incorrect for some mods?

**Comment by WittleWolfie** [comment]
Oh yeah I see your point xD I actually had this thought as well. We should absolutely include year.

**Comment by WittleWolfie** [comment]
Also I only just realized you filed this on the wrong mod :P I'm pretty sure you mean to file on ModFinder not ModMenu. Closing out but fix for ModFinder incoming.
